[package]
name = "arnis-rust"
version = "2.0.0-dev"
edition = "2021"
description = "Arnis - Generate real life cities in Minecraft"
homepage = "https://github.com/louis-e/arnis"
repository = "https://github.com/louis-e/arnis"
license = "GPL-3.0"
readme = "README.md"

[dependencies]
clap = { version = "4.1", features = ["derive"] }
fastanvil = "0.31.0"
fastnbt = "2.5.0"
once_cell = "1.19.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"