name: Build and Release Arnis

on:
  release:
    types: [created]

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            binary_name: arnis.exe
            artifact_name: arnis-windows-x64.exe
          - os: windows-latest
            target: i686-pc-windows-msvc
            binary_name: arnis.exe
            artifact_name: arnis-windows-x86.exe
          - os: ubuntu-24.04
            target: x86_64-unknown-linux-gnu
            binary_name: arnis
            artifact_name: arnis-linux-x64
          - os: ubuntu-24.04
            target: i686-unknown-linux-gnu
            binary_name: arnis
            artifact_name: arnis-linux-x86

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Rust
      uses: dtolnay/rust-toolchain@v1
      with:
        toolchain: stable
        targets: ${{ matrix.target }}

    - name: Install Linux x64 dependencies
      if: matrix.os == 'ubuntu-24.04' && matrix.target == 'x86_64-unknown-linux-gnu'
      run: |
        sudo apt update
        sudo apt install -y software-properties-common
        sudo add-apt-repository universe
        sudo apt update
        sudo apt install -y libgtk-3-dev build-essential pkg-config libglib2.0-dev libsoup-3.0-dev libwebkit2gtk-4.1-dev
        echo "PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig" >> $GITHUB_ENV

    - name: Install Linux x86 dependencies
      if: matrix.os == 'ubuntu-24.04' && matrix.target == 'i686-unknown-linux-gnu'
      run: |
        sudo dpkg --add-architecture i386
        sudo apt update
        sudo apt install -y gcc-multilib g++-multilib
        sudo apt install -y libgtk-3-dev:i386 libglib2.0-dev:i386 libsoup-3.0-dev:i386 libwebkit2gtk-4.1-dev:i386
        echo "PKG_CONFIG_PATH=/usr/lib/i386-linux-gnu/pkgconfig" >> $GITHUB_ENV
        echo "CARGO_TARGET_I686_UNKNOWN_LINUX_GNU_LINKER=gcc" >> $GITHUB_ENV

    - name: Install dependencies
      run: cargo fetch --locked

    - name: Build
      run: cargo build --frozen --release --target ${{ matrix.target }}

    - name: Prepare binary
      run: |
        mkdir -p artifacts
        if [ "${{ matrix.os }}" = "windows-latest" ]; then
          cp target/${{ matrix.target }}/release/${{ matrix.binary_name }} artifacts/${{ matrix.artifact_name }}
        else
          cp target/${{ matrix.target }}/release/${{ matrix.binary_name }} artifacts/${{ matrix.artifact_name }}
        fi

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.artifact_name }}
        path: artifacts/${{ matrix.artifact_name }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Create artifact directory
      run: mkdir -p artifacts

    - name: Download all artifacts
      uses: actions/download-artifact@v3
      with:
        path: artifacts

    - name: Prepare artifacts for release
      run: |
        cd artifacts
        find . -type f -not -name "*.exe" -exec chmod +x {} \;
        # Move all files to current directory
        find . -mindepth 2 -type f -exec mv {} . \;

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          artifacts/arnis-windows-x64.exe
          artifacts/arnis-windows-x86.exe
          artifacts/arnis-linux-x64
          artifacts/arnis-linux-x86
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
